title: Sophia Sun
name: "Sophia's Blog"
author: Sophia Sun
twitter_username: _yokaii_
baseurl: "/"
description: bleep bloop tech blog.
profile_url: "http://guiguiguiguigui.github.io"
permalink: /:title
show_drafts: false
future: false
category: "post"
img: ""


# Build settings
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->
plugins:
  - jekyll-feed
  - jekyll-archives
  - jekyll-twitter-plugin
exclude:
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
sass:
  sass_dir: _sass
